### ISSUE TITLE
View results solution table does not appear

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/whattodo#33]
The "Statistics describing solution" table appears blank on the app. The solution file in download seems fine. It just doesn't appear to be translating to the app interface.

**Comment by jeffreyhanson** [comment]
Yeah that's not right  - the table shouldn't ever be blank. Thanks for catching this!

**Comment by jeffreyhanson** [comment]
I'm sorry, I'm having trouble reproducing this - does this issue occur when you first generate a solution, or when toggling between multiple solutions?

**Comment by jeffreyhanson** [comment]
@josephrbennett, I'm having trouble reproducing this issue. To test if it was a timeout issue, I tried (i) opening the app, (ii) leaving it for 15 mins, and then (iii) using it again. Since the app was still functional after receiving no inputs during this time, I think we can rule out possible timeouts being the cause? So, I'm guessing the error could be due to some combination of inputs/button presses. Could you please provide more information on the steps needed for this bug to manifest?

**Comment by jeffreyhanson** [comment]
Is this the bug you encoutnered? If so, I can reproduce it by resizing the browser after opening the table (i.e. resizing the browser window so that it is really tiny, and then resizing it so that it is encompasses the entire screen).

![image](https://user-images.githubusercontent.com/3610005/155902655-7cbb2057-6906-4244-8612-2c225627bdef.png)

**Comment by jeffreyhanson** [comment]
I've pushed a patch to fix this issue. If the issue described above isn't the same one you encountered @josephrbennett, please feel free to re-open this issue.
